@startuml

Actor User as act 
Participant System as sys

activate act

act -> sys : clicks confirmation link
deactivate act
activate sys

sys --> act : requests password

deactivate sys
activate act

act -> sys : inputs requested information
deactivate act
activate sys

sys --> act : success email
deactivate sys
activate act




@enduml