image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            caches:
              - dotnetcore
            script:
              - export PROJECT_NAME=backoffice/src/projeto_integrador_lapr5.sln
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore $PROJECT_NAME
              - dotnet build $PROJECT_NAME
        - step:
            name: Lint the code
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=backoffice/src/projeto_integrador_lapr5.sln
              - export REPORTS_PATH=linter-reports
              - dotnet new tool-manifest
              - dotnet tool install JetBrains.ReSharper.GlobalTools
              - dotnet tool restore
              - dotnet jb inspectcode ${SOLUTION_NAME} --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
            artifacts:
              - linter-reports/**
        - step:
            name: Test
            caches:
              - dotnetcore
            script:
              - cd backoffice/test
              - dotnet restore
              - dotnet build
              - dotnet test
        
