@startuml

actor Doctor as doctor
actor System as sys


activate doctor

doctor -> sys : requests specific medical condition
deactivate doctor
activate sys

sys --> doctor : requests query data
deactivate sys
activate doctor

doctor -> sys : sends query data
deactivate doctor
activate sys

sys --> doctor : shows requested medical condition
deactivate sys
activate doctor

@enduml