@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Doctor
Participant System

activate Doctor

Doctor -> System : requests to edit appointment
deactivate Doctor
activate System

System --> Doctor : displays appointments
deactivate System
activate Doctor

Doctor -> System : chooses appointment
deactivate Doctor
activate System

System -> Doctor : requests for operation request, room and date
deactivate System
activate Doctor

Doctor --> System : inserts information
deactivate Doctor
activate System

System -> Doctor : requests for assigned staff for operation request
deactivate System
activate Doctor

Doctor --> System : picks available staff and creates appointment
deactivate Doctor
activate System

System --> Doctor : success information message
deactivate System
activate Doctor

@enduml