@startuml US23_SSD

title System Sequence Diagram - US 23

autonumber

actor "Admin" as adm
participant "System" as app

activate adm

	adm -> app : filter operation types
	activate app
		app --> adm : request filter options
	deactivate app

	adm -> app : inputs requested info
	activate app
		app --> adm : lists operation types
	deactivate app

deactivate adm


@enduml