@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Routing as route
participant ResetPasswordController as ctrl
participant TokenService
participant TokenFactory as tokenFac
participant TokenRepository as tokenRepo
participant UserRepository as usrRepo
participant EmailService as emailSvc

-> route : POST(email)
activate route

route -> ctrl : GeneratePasswordResetToken(email)

deactivate route
activate ctrl




ctrl -> TokenService : GeneratePasswordResetToken(email)

deactivate ctrl
activate TokenService

TokenService -> usrRepo : GetById(username)
deactivate TokenService
activate usrRepo

usrRepo --> TokenService : user
deactivate usrRepo
activate TokenService

TokenService -> tokenFac : getToken(userDTO)

deactivate TokenService
activate tokenFac

tokenFac --> TokenService : token
deactivate tokenFac

activate TokenService
 TokenService -> TokenDTO** : create()

 TokenService --> ctrl : tokenDTO
 deactivate TokenService

 activate ctrl



 ctrl -> emailSvc : sendActivationNotification(emailAddress, tokenDTO)
 deactivate ctrl
 activate emailSvc

 emailSvc --> ctrl : opResult
 deactivate emailSvc
 activate ctrl

route <-- ctrl : opResultMessage
deactivate ctrl
activate route
<-- route : opResultMessage
deactivate route


@enduml