@startuml

participant Routing as route
participant ResetPasswordController as ctrl
participant UserService as tokenSvc
participant PasswordActivationService as passSvc
participant UserDto as dto
participant UserRepository as tokenRepo


-> route : POST(password, token)

activate route
route -> ctrl : ResetPassword(password, token)

deactivate route
activate ctrl
REF OVER ctrl
REFER to Generic AUTH SD
end
ctrl -> tokenSvc : GetByIdAsync(userId)

deactivate ctrl
activate tokenSvc

tokenSvc -> tokenRepo: getById(UserId)
deactivate tokenSvc
activate tokenRepo

tokenRepo --> tokenSvc : token
deactivate tokenRepo

activate tokenSvc
tokenSvc --> ctrl : tokenUser

deactivate tokenSvc

activate ctrl

ctrl -> passSvc : resetPassword(password, user)
deactivate ctrl
activate passSvc

passSvc -> UserRepository : save(user)
deactivate
activate UserRepository

UserRepository --> passSvc : user
deactivate

activate passSvc

passSvc -> dto**: user.toDto()

passSvc --> ctrl : userDto
deactivate passSvc

activate ctrl
ctrl -> route : userDto
deactivate
activate route

<-- route : userDto
deactivate

@enduml